### ISSUE TITLE
Duda sobre el proyecto

### ISSUE THREAD

**Issue by EfraMP** [EveliaCoss/RNAseq_classFEB2023#1]
¿En qué idioma debemos de entregarlo?

**Comment by EveliaCoss** [comment]
Español o ingles, a tu preferencia

**Comment by EfraMP** [comment]
Perfecto, gracias!

Otra duda, de dónde puedo descargar la versión actualizada de estos archivos??

![image](https://user-images.githubusercontent.com/67405824/224389846-699f95e1-afde-4ef0-b045-bfc0888a16d9.png)

**Comment by EveliaCoss** [comment]
Estoy segura que yo no les di esos archivos, asi que no sabria contestarte eso

**Comment by EveliaCoss** [comment]
Pero si buscas el tx2gene de humano, puedes encontrarlo en google 
https://www.biostars.org/p/422750/

**Comment by EfraMP** [comment]
Hecho! Gracias!
